language: node_js
node_js:
- '0.10'
- '0.11'
env:
  global:
  - secure: Hk0fr90+nV9eXFsjRWFFPsphz3bha38FIr842FHm4B294MY6bX28vXTspdzPoSmDxGtFnSHFJBnFCTPH84amxoVU6A1TRu1iy2ZaGQ9CgatvxL9n3fw57C9vFBG54hLWoWnNgCIqmIkDR78UODt+U6qRdYg78jyZJHm9Qcd8Gs8=
  - secure: h2xCBuTgUHq6RAdIwuMmKMhiLelZhELr7KnCZ3SQxyjl76RQshcTzeEGAYgUZhVeMwRmasSPEo5QNtPrMfs3mBOkcZIv/1KvTzzT9VuCNfMGf5gAXemJmZg9DOnn4B+1VmClRZxIFBB2+bNa7sURefYxScaLeTKDilHTIOSwJEo=
  - secure: RQwN5W/hulj/uDToLwIHr5I1QPmsJsAHw3uyjSKu3FDkpP6I5ilBXLb/4OnL7yzRGHgEOtm84nnywYVbEo2yDaWN8GrzfvwvKXlS5tG3RzKsE1tYgdL0Oo2CULV2tGAUHK5y8HOE1GSbMP5yOKTxy5oR0esjA5uZa8+KAO8n81g=
  - secure: ZKyH2oakSR9gfUjg2KcQl5FEY/+VobLS0El4ivjU65OFJhLPunegF3+YMeeT/aOyOBuTP9BakqjO4XFVNsZmC+a5ZJXOrfNv3w+eVBM7pZrLA5IPSRNj6bt4yzKoGgGBsT6U0xRR549xCZ6duuTjATx04p4JI5AEe71NI0t/KO4=
