language: node_js
node_js:
- '0.10'
- '0.11'
env:
  global:
  - secure: jM7gKXBuH1ytMbqVimXEzhqVFplU2WqUswgmytb1pDMnBwMsVtsVee9MupxEPwIHpbVbmZjnU4gm0AtOk8lss2nzaRNmBy3cfkbNtKqMqwhJ70Y+vp/pZYCQxHoY75zUkCZ5r/70BLCBM5U9WZGWZkdDInwnezayoWXzMVdH8jw=
  - secure: SXY6jaVmuQmVzZSzHzi0Z/Jlb6AtD8du9QaTG3HLu7iBysgwphcnpUR0tQPcw5fzOkOgyrs2muUd/Jv07OChdzVd0cQPAH9bcUl4vjRNiYK5CjjJi8HHDJ/P8E+4mCN7hmUkF+bJrsuC9ugEoV8TczaxbvdJepdzyUS35NicZ9c=
  - secure: caXVAkfIzuoTRDmKYNKxhl6RVTpUwXjLGJ/TPE2RKH+ox0xVEqH4G51rLWnJLvp4G5Fq5Gealcv5EhiKj0do0KUqadxQZbJxjCX62oFFNfs3hNv9RFq/Ry1NfkYV86UdHSxBhGacdwQSGHyD9WHgpV65JWze5lnP2iH1S3mj5wE=
  - secure: J0pfvEgw3mcZYW1ajLouQBuRPmfslbhxwhzuANEwMXpwLGY5nVZA/MFKGwg8zsG8hkgHyG93ObqyVtIIvJg9GYcTb1IQaiUVp3zTLU7FpRR1o6CmxAec78ktLC16B4oeKuh3G4RpjXjqnCITnrE6+UhNfejSTLIGljoyFfsBskg=
