language: node_js
node_js:
- '0.10'
- '0.11'
env:
  global:
  - secure: NRQCwVceRgwA4ZG5vNHZM1qW6UZ3tr4V1SZ78F/1cHKTFjFk5g4t1gp225a6xBb8FeL+JSufQG66amEC23uwSFfB5z1vULr7/eBlOfNpZTj/2W8jFzo2Z6Q8nQRpdZhCHSdP2E89aIIyiKIJWQVGsvm76z/14JxGaD/+VqKxdXA=
  - secure: R0NrQNNm/kBeekj1fGTE9c1omnpP9MjQxhz9LK/6OOJmS5sCcYErNsf2n4G7r/d23hmelWoONTpF2rAn/lrnwGfOYh6zJ42V/kK+RWvzvTZMd8XJDrOX6TfT17AQfxZ4RXVHk/dBY+FAAr8Cgbduemm8T8eXt54yj0lIGGgHAro=
  - secure: C8Yo6SvnAHuz3qeJEEXA1RVvr2VNDVN6SJX/tsRrLo0MkmltT5vKEwwCYDxU3hNarDBfAN9xn0c1jv6OW2kLE/50KBe4U3wBAlPYdr7bMWVBWL1e5ZVSyhr/RfYL6DfT2GUAaejMq7N0RKaowLel1eFIK6D0nCiiYyUKP+h/+PY=
  - secure: Uik9ug/tT8KfSFQfRnBbfFgXSFW3qZJx3A/qHuCET0s11rS2ZFWxCJkHr8+W/RTWl/cEFeoIYRwI/y66WCKozg56vztTJzVcHpfCWM205/Y76CSVxf67lcf6aCVPLbumkJPkm+yyZFfvvYHn4sQ+9vJ7+Wjm7MUr6UOONWJIh+Q=
