language: node_js
node_js:
- '0.10'
- '0.11'
env:
  global:
  - secure: BVCjkDDs3yh95nth8eIW3ZMg+QGwPq9FbCrayPA+9/DjVQdq3AAqofXegqGO31EQXov2qXytaHca2fMxJcFuiV7Pf5aXKKaLAUmq7+p8s7gkY7nScVAfpKlebr/whQYfIk0drLKCkGhCZ1g0X2tbqncApb8IjcyYEkoPGiICzJU=
  - secure: Agx+rYKjJ+3DYwk5sBjTGc6uWinC0jchXowqvC1t8HZdWDXjMCA6VAVFvZ+VXoFiRASQyw3CyYu/7kqjjqlLZ9hcALabkzrnywMhfwaNRu/EsaAXxs1BRX2kz9k2O07LkTfdgqbd71PLsjlop7f7LzYPFTUMHbDywbF3qA5FOYU=
  - secure: ERmIiDEmMXp6DMhHXowpidi6hPkfgV2WcvYOk2mgnJCG3OrH3nJTqSdlWw5z5sDfUYbhdfwbioy1ANJ8JDlG881FPZsRMS64eZ5s0nji8J4IhZWHF1SHzNRpGCZJOSKb/P+bS+7uR5umZUrCvO8XqtI+eMDjTy5ZRNb9NVwJJI4=
  - secure: LfvfCqwIyJyVeiv1s/HpxFg24aug5vzSeM6hXO/A4MIPJ7pNxVQOjhdG6ZwEgi23irJLVW56ee7hESggMJWSBO67KlX1pbmOVT+m5pGe/w5lkB4Hj4Y9j7atKH/rb4hTFT7kP3XOOlICuvVGLO0Y5sVoUcFhF+R5xuyiNHLuPP8=
